apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: coolstore-api-auth-policy-binding
  namespace: bookinfo
spec:
  policies:
    - name: coolstore-api-auth-policy
      namespace: bookinfo
  services:
    - name: details
      namespace: bookinfo
