apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: coolstore-api-auth-policy-binding
  namespace: store
spec:
  policies:
    - name: coolstore-api-auth-policy
      namespace: store
  services:
    - name: products
      namespace: store
