apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: products-default
  namespace: store
spec:
  destination:
    name: products
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100