apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: test-recommendations-for-user-jason
spec:
  match:
    request:
      headers:
        cookie:
          regex: ^(.*?;)?(user=jason)(;.*)?$
  destination:
    name: products
    namespace: store
  precedence: 2
  route:
  - labels:
      version: recommendations
